### ISSUE TITLE
can not find the tif profiles in the container

### ISSUE THREAD

**Issue by MrFoxwho** [motokimura/spacenet_building_detection#1]
The terminal can not find the tif files in the container directory of ../../data/processedBuildingLabels/3band"

**Comment by motokimura** [comment]
Did you download SpaceNet data from AWS?
https://github.com/motokimura/spacenet_building_detection#1-download-spacenet-dataset

If so, I suggest you to check `3band` directory exists in the correct path.

**Comment by MrFoxwho** [comment]
Thank you. I fix the error by creating a “buildingMaskImages” folder myself.

**Comment by MrFoxwho** [comment]
> Did you download SpaceNet data from AWS?
> https://github.com/motokimura/spacenet_building_detection#1-download-spacenet-dataset
> 
> If so, I suggest you to check `3band` directory exists in the correct path.

Thank you. I have fixed this error by creating a folder named”buildingMaskImages”. 
By the way, could you tell me the password of jupyter notebook in the container ? I can not use it when opening local host:8888.

**Comment by motokimura** [comment]
I just realized I should have made `buildingMaskImages` in advance thanks to your feedback. Thanks.

Default password is `passw0rd` as written in `docker/Dockerfile`.
https://github.com/motokimura/spacenet_building_detection/blob/a9442b86b6cbb978904eb19bbf26e71700673fd1/docker/Dockerfile#L65

**Comment by motokimura** [comment]
If you run the container in remote server like AWS, GCP, etc., I recommend you to change this password just in case.

**Comment by MrFoxwho** [comment]
> I just realized I should have made `buildingMaskImages` in advance thanks to your feedback. Thanks.
> 
> Default password is `passw0rd` as written in `docker/Dockerfile`.
> https://github.com/motokimura/spacenet_building_detection/blob/a9442b86b6cbb978904eb19bbf26e71700673fd1/docker/Dockerfile#L65

Thanks a lot！

**Comment by motokimura** [comment]
Thanks for your feedback!. I will close this issue after fixing a bug.
