### ISSUE TITLE
ModuleNotFoundError: No module named 'gdal'

### ISSUE THREAD

**Issue by rajabi1372** [motokimura/spacenet_building_detection#2]
Hi
I encountered this error in running the program:

**ModuleNotFoundError: No module named 'gdal'**

could you please help me out?

**Comment by motokimura** [comment]
Are you running the script in Docker container?

**Comment by rajabi1372** [comment]
can you guide me?

**Comment by rajabi1372** [comment]
I dont know,
can you guide me?

**Comment by rajabi1372** [comment]
Can you explain what should I do?
please,

**Comment by motokimura** [comment]
Install dependencies.
https://github.com/motokimura/spacenet_building_detection#dependency

Then do these step-by-step.
https://github.com/motokimura/spacenet_building_detection#usage
