### ISSUE TITLE
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by manapshymyr-OB** [motokimura/spacenet_building_detection#4]
When I try to start training it is giving me an error cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)
[| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:21:00.0  On |                  N/A |
| 35%   31C    P8     6W / 260W |    425MiB / 11016MiB |      4%      Default |](url)

**Comment by motokimura** [comment]
Sorry for my late response. 
I'm not sure but cuda version defined in Dockerfile (v8.0) may be too old for your video card.
