### ISSUE TITLE
Dockerfile build - miniconda issue

### ISSUE THREAD

**Issue by plusbest** [motokimura/spacenet_building_detection#5]
The Dockerfile's miniconda curl returns an empty repo and fails because the current line doesn't have the 'allow redirect' tag. You may want to update the conda RUN command to include the **-L** tag.
 
From:
`RUN curl -o ~/miniconda.sh `

To:
`RUN curl -L -o ~/miniconda.sh`

Solution credit found [here](https://stackoverflow.com/questions/63359198/building-docker-opt-conda-bin-conda-not-found/63367463#63367463?newreg=4c099d670eea41d6b36e009d95d5b7a9)

**Comment by motokimura** [comment]
Thanks for reporting.
I will fix this when I have time.
Your PR is more than welcome.

**Comment by plusbest** [comment]
Pleasure is all mine. Thank you for an amazing project.
